[package]
name = "sel"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [] }
vulkano = "0.33.0"
vulkano-shaders = "0.33.0"
image = "0.24"

[profile.dev]
# Reduce performance artifacts
opt-level = 1
